# Generated by Django 6.1 on 2026-08-26 18:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FareGrid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('pickup_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', 'price_per_km'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('active',), name='unique_active_fare_grid')],
            },
        ),
    ]
