# Generated by Django 6.1 on 2026-08-26 19:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
        ('taxis', '0002_vehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('departure_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('departure_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('arrival_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('arrival_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('distance_km', models.DecimalField(decimal_places=3, max_digits=9)),
                ('estimated_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('status', models.CharField(choices=[('WAITING', 'en attente'), ('ACCEPTED', 'acceptée'), ('IN_PROGRESS', 'en cours'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'annulée')], default='WAITING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='taxis.driver')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'status'],
            },
        ),
    ]
