# Generated by Django 6.1 on 2026-08-27 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_ride'),
        ('taxis', '0002_vehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ride',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['WAITING', 'ACCEPTED', 'IN_PROGRESS'])), fields=('passenger',), name='unique_active_ride_per_passenger'),
        ),
        migrations.AddConstraint(
            model_name='ride',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['ACCEPTED', 'IN_PROGRESS'])), fields=('driver',), name='unique_active_ride_per_driver'),
        ),
    ]
