# Generated by Django 6.1 on 2026-08-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Passager'), ('DRIVER', 'Chauffeur'), ('ADMIN', 'Administrateur')], default='CLIENT', max_length=30),
        ),
    ]
